name: image-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - tensorflow
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - rise
   - pip:
    - jupyter-contrib-nbextensions
    - opencv-python-headless
