name: image-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - tensorflow
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - rise
  - cv2
  - pip:
    - jupyter-contrib-nbextensions
